import chromadb
import requests


# Local folder where Chroma persists its database
CHROMA_PATH = "chroma_db"

# Name of the Chroma collection created during ingestion
COLLECTION_NAME = "programming_notes"

# Local Ollama models
EMBED_MODEL = "nomic-embed-text"
LLM_MODEL = "llama3"


def generate_embedding(text: str) -> list[float]:
    """Generate an embedding for a given text using Ollama.

    Args:
        text: Input text to embed.

    Returns:
        A numeric vector representing the semantic meaning of the text.

    Raises:
        requests.HTTPError: If Ollama returns an unsuccessful response.
    """
    response = requests.post(
        "http://localhost:11434/api/embeddings",
        json={
            "model": EMBED_MODEL,
            "prompt": text
        },
        timeout=60
    )

    response.raise_for_status()

    # The Ollama API returns a JSON response with an "embedding" field
    return response.json()["embedding"]


def load_collection():
    """Load the persistent Chroma collection.

    Returns:
        A Chroma collection object already stored on disk.

    Notes:
        This assumes that ingest.py has already been executed and
        the collection exists inside chroma_db/.
    """
    client = chromadb.PersistentClient(path=CHROMA_PATH)
    return client.get_collection(name=COLLECTION_NAME)


def search_similar_chunks(question: str, top_k: int = 5) -> dict:
    """Retrieve the most relevant chunks for a user question.

    Args:
        question: User question in natural language.
        top_k: Number of chunks to retrieve from Chroma.

    Returns:
        A dictionary containing query results from Chroma.

    How it works:
        1. The question is converted into an embedding.
        2. That embedding is compared against all stored chunk embeddings.
        3. Chroma returns the most semantically similar chunks.
    """
    collection = load_collection()

    # Convert the user question into a numeric vector
    question_embedding = generate_embedding(question)

    # Search for the closest chunks in the vector database
    results = collection.query(
        query_embeddings=[question_embedding],
        n_results=top_k
    )

    return results


def build_prompt(question: str, retrieved_chunks: list[str]) -> str:
    """Build the final prompt sent to the language model.

    Args:
        question: Original user question.
        retrieved_chunks: Document chunks retrieved from Chroma.

    Returns:
        A prompt containing context + question.

    Notes:
        The LLM must answer only from the provided context.
        This is what makes the system RAG instead of pure generation.
    """
    # Join all retrieved chunks into a single context block
    context = "\n\n".join(retrieved_chunks)

    prompt = f"""
You are a helpful assistant answering questions using only the provided context.

If the answer is not in the context, say:
"I do not know based on the provided context."

Context:
{context}

Question:
{question}

Answer:
""".strip()

    return prompt


def generate_answer(prompt: str) -> str:
    """Generate the final answer using the local language model.

    Args:
        prompt: Prompt containing both context and user question.

    Returns:
        Final response generated by the LLM.

    Raises:
        requests.HTTPError: If Ollama returns an unsuccessful response.
    """
    response = requests.post(
        "http://localhost:11434/api/generate",
        json={
            "model": LLM_MODEL,
            "prompt": prompt,
            "stream": False
        },
        timeout=120
    )

    response.raise_for_status()

    # The final generated answer is returned inside the "response" field
    return response.json()["response"]


def ask_rag(question: str, top_k: int = 5) -> dict:
    """Run the complete RAG pipeline for a user question.

    Args:
        question: User question.
        top_k: Number of chunks to retrieve.

    Returns:
        A dictionary containing:
            - answer: final generated answer
            - documents: retrieved chunks
            - metadatas: metadata of retrieved chunks
            - distances: vector distances for each chunk

    Pipeline:
        1. Retrieve relevant chunks from Chroma.
        2. Build a prompt using those chunks.
        3. Ask the LLM to answer using only that context.
    """
    results = search_similar_chunks(question, top_k=top_k)

    # Chroma returns nested lists because it supports batch querying.
    # We only query one question, so we access the first element.
    documents = results.get("documents", [[]])[0]
    metadatas = results.get("metadatas", [[]])[0]
    distances = results.get("distances", [[]])[0]

    # Build the final context-aware prompt
    prompt = build_prompt(question, documents)

    # Ask the local LLM to generate an answer
    answer = generate_answer(prompt)

    return {
        "answer": answer,
        "documents": documents,
        "metadatas": metadatas,
        "distances": distances
    }


def main() -> None:
    """Run the local RAG system from the command line."""
    print("Local RAG ready.")
    print("Write a question about the indexed PDF.\n")

    question = input("Question: ").strip()

    if not question:
        print("No question provided.")
        return

    result = ask_rag(question, top_k=5)

    print("\nAnswer:\n")
    print(result["answer"])


if __name__ == "__main__":
    main()